---
title: "03 - Data Transformation"
book: R4DS
link: "[https://r4ds.hadley.nz/data-transform.html](https://r4ds.hadley.nz/data-transform.html)"
engine: knitr
---

## Introduction

```{r}
library(dplyr)
library(nycflights13)
flights <- nycflights13::flights
```

## Selecting Columns

```{r}
flights %>% select(year, month, day, dep_delay, arr_delay)
```

## Filtering Rows

```{r}
flights %>% filter(month == 1, day == 1)
```

## Arranging Rows

```{r}
flights %>% arrange(desc(dep_delay))
```

## Creating New Variables

```{r}
flights %>% mutate(speed = distance / air_time * 60)
```

## Renaming Columns

```{r}
flights %>% rename(departure_delay = dep_delay, arrival_delay = arr_delay)
```

## Relocating Columns

```{r}
flights %>% relocate(dep_delay, arr_delay, .before = distance)
```

## Summarizing Data

```{r}
flights %>% group_by(carrier) %>% summarize(avg_delay = mean(dep_delay, na.rm = TRUE))
```

## Counting Observations

```{r}
flights %>% count(carrier)
```

## Using Pipes

```{r}
flights %>% 
  filter(month == 1, day == 1) %>% 
  select(year, month, day, carrier, flight)
```

## Combining Multiple Transformations

```{r}
flights %>% 
  group_by(carrier) %>% 
  summarize(avg_delay = mean(dep_delay, na.rm = TRUE)) %>% 
  arrange(desc(avg_delay))
```

## Conclusion

```{r}
summary(flights)
```
