---
title: "Lavoro di Gruppo 3 - Metanalisi"
subtitle: ""
author: ""
format: html
---

# Dataset

Questo lavoro di gruppo richiede di effettuare una metanalisi su un dataset che raccoglie diversi studi di efficacia della psicoterapia cognitivo-comportamentale per i disturbi d'ansia. In questo caso per una tipologia specifica di disturbi d'ansia ovvero l'ansia sociale.

> Ansia sociale (o fobia sociale) è un disturbo d’ansia caratterizzato da una paura intensa e persistente di essere giudicati negativamente o di sentirsi in imbarazzo in situazioni sociali o prestazionali. Le persone con ansia sociale tendono a evitare queste situazioni o le affrontano con notevole disagio, compromettendo la qualità della vita e il funzionamento quotidiano (American Psychiatric Association, 2013).

Il dataset si trova nella repository principale del corso dentro la cartella `teamworks/03-meta-analysis/social-anxiety-psychotherapy.csv`.

```{r}
dat <- read.csv("social-anxiety-psychotherapy.csv")
head(dat)
```

Le variabili sono le seguenti:

- `id`: identificativo dell'effetto
- `paper`: identificativo del paper
- `g`: effect size (Hedges's $g$)
- `se`: effect size standard error
- `year`: anno di pubblicazione
- `n`: sample size
- `recruitement`: luogo di reclutamente dei pazienti/controlli
- `format`: modalità di psicoterapia
- `intervention_type`: tipo di psicoterapia
- `control_tupe`: tipologia di gruppo di controllo
- `p_women`: percentuale di donne nel campione
- `sessions`: numero di sessioni di psicoterapia
- `country`: dove è stato eseguito lo studio
- `age_group`: categoria d'età
- `mean_age`: età media del campione
- `risk_bias`: livello di rischio che quello studio abbia delle problematiche che potrebbero influenzare i risultati

# Steps

Gli step da eseguire sono i seguenti:

1. descrizione dettagliata del dataset in modo discorsivo con statistiche descrittive e grafici adeguati ad ogni tipo di variabile
2. effettuare la metanalisi usando diversi modelli e confrontando i risultati.
    - modello a due livelli random-effects e fixed-effects
    - modello a due livelli random-effects e fixed-effects aggregando gli effetti nello stesso paper. Si veda il capitolo `borenstein-aggregation.pdf` ed implementare manualmente la formula adeguata.
    - modello a tre livelli per gestire la struttura nested dei dati
3. valutare e commentare l'effetto dei moderatori e se possibile della loro interazione sia per il modello a due livelli che quello a tre livelli
4. valutare il publication bias usando tutti i metodi che sono stati presentati a lezione. Per quanto riguarda i selection models scegliere almeno 3 modelli diversi e confrontare i risultati.
5. produrre grafici e tabelle per ogni risultato. in particolare:
    - riprodurre i forest plot e funnel plot usando `ggplot2` (senza usare pacchetti aggiuntivi) che siano più simili possibili a quelli di `metafor`
    - produrre dei grafici per l'effetto dei moderatori che rappresentino i risultati in modo adeguato
    - produrre delle tabelle che rappresentino i risultati in modo adeguato. Utilizzare il pacchetto e la modalità che si preferisce.
6. implementare senza utilizzare pacchetti aggiuntivi un test di permutazione per il modello random-effects a due livelli per l'effetto generale
7. valutare per il modello a due livelli random-effects (senza aggregare) l'impatto dei singoli paper con una leave-one-out analysis con relativa rappresentazione grafica

# Aspetti generali

- Ogni step deve essere accompagnato da una spiegazione narrativa e dove pertinente da rappresentazioni grafiche e tabelle che spieghino in maniera chiara i risultati
- Tutti gli step devono essere prodotti in un documento Quarto (html o pdf) riproducibile e self-contained
- Chi vuole può preparare una presentazione in Quarto da utilizzare durante l'esame
