---
title: "Efficacia psicoterapia per Disturbo d'Ansia Sociale"
subtitle: "Metanalisi"
format: html
---

# Dataset

Questo lavoro di gruppo richiede di effettuare una metanalisi su un dataset che raccoglie diversi studi di efficacia della psicoterapia cognitivo-comportamentale per i disturbi d'ansia. In questo caso per una tipologia specifica di disturbi d'ansia ovvero l'ansia sociale.

> Ansia sociale (o fobia sociale) è un disturbo d’ansia caratterizzato da una paura intensa e persistente di essere giudicati negativamente o di sentirsi in imbarazzo in situazioni sociali o prestazionali. Le persone con ansia sociale tendono a evitare queste situazioni o le affrontano con notevole disagio, compromettendo la qualità della vita e il funzionamento quotidiano (American Psychiatric Association, 2013).

Il dataset si trova nella repository principale del corso dentro la cartella `teamworks/03-meta-analysis/data`.

```{r}
dat <- read.csv("social-anxiety-psychotherapy.csv")
```

descrizione variabili

# Steps

Gli step da eseguire sono i seguenti:

- **descrizione dettagliata del dataset** in modo discorsivo con statistiche descrittive e grafici adeguati ad ogni tipo di variabile.
