---
title: "Lavoro di Gruppo 2 - Analisi di dati ERP"
subtitle: ""
author: ""
format: html
---

# Dataset

Questo lavoro di gruppo richiede di effettuare l'analisi di un dataset ERP.

Il dataset è parte di [ERPcore](https://erpinfo.org/erp-core), e consiste in un esperimento con 40 partecipanti esposti alla visione passiva di quattro tipologie di stimoli:\

- Volti
- Volti scrambled
- Automobili
- Automobili scrambled

Questo tipo di paradigma è tipicamente usato per studiare i processi corticali sottostanti l'elaborazione di volti, e si associano ad uno specifico potenziale evento-relato, la N170.

I dati sono quelli già usati nelle esercitazioni sulla visualizzazione di dati ERP, quindi sono già preprocessati e privi di artefatti. In alternativa potete nuovamente effettuare il download a [questo link](https://drive.google.com/file/d/14CIu2VmW1gJkRbexYdy5wH4n1WoAVCTy/view?usp=sharing).

# Step da eseguire per lo svolgimento del progetto

1. Importare i dati in un unico dataframe in R
2. Eseguire l'esplorazione del dataset rispetto alla **differenza tra facce e facce scrambled** su tutti gli elettrodi\
    2a. Creare una rappresentazione grafica delle waveform delle due condizioni sperimentali per tutti gli elettrodi
    2b. Riportare le statistiche descrittive per le due condizioni sperimentali nella finestra 150-190 ms (per tutti gli elettrodi)
3. Eseguire l'analisi statistica con un mixed-effects model per spiegare la **differenza tra facce e facce scrambled** nella finestra 150-190 ms in quattro cluster di elettrodi: Cluster Anteriore Destro (F4,FC4, F8), Cluster Anteriore Sinistro (F3, FC3, F7), Cluster Posteriore Destro (PO8, P8, PO4), Cluster Posteriore Sinistro (PO7, P7, PO3)
4. Eseguire l'analisi statistica con l'approccio _mass univariate_ con la gestione dei confronti multipli attraverso l'approccio _cluster-mass permutation_ per spiegare la **differenza tra facce e facce scrambled** usando tutti gli elettrodi e tutti i time points a disposizione.
5. Commentare i risultati di entrambi i metodi, evidenziando pro e contro di ognuno

# Aspetti generali

- Ogni step deve essere accompagnato da una spiegazione narrativa e dove pertinente da rappresentazioni grafiche e tabelle che spieghino in maniera chiara i risultati
- Tutti gli step devono essere prodotti in un documento Quarto (html o pdf) riproducibile e self-contained
- Chi vuole può preparare una presentazione in Quarto da utilizzare durante l'esame
